### ISSUE TITLE
Not really an issue, just a codeshare opportunity

### ISSUE THREAD

**Issue by bradchesney79** [bogdanvlviv/i-vagrant#1]
I'm working on a similar project and wanted to ping you.

My email is bradchesney79@gmail.com. I was looking at your jslint stuff that I may heavily borrow from. That airbnb package is fairly boss.

I keep forgetting to make a list of project like ours. I'll do it now, adding a link to your repo in my README.md.

**Comment by bogdanvlviv** [comment]
Feel free to do it
